services:
  file_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_api
    ports:
      - "8005:8000"
    environment:
      - BASE_DIR=/app/data
    volumes:
      - ./scratch/vault:/app/data
    restart: unless-stopped
    networks:
      - mimir_default
      - default

networks:
  mimir_default:
    name: mimir_default
    external: true
